---
# file: grafana/tasks/main.yml
#
# tasks file
#

- include_tasks: "setup-{{ansible_os_family}}.yml"

- name: Ensure integrity of grafana configuration.
  template:
    src: 'grafana.ini.j2'
    dest: "{{ grafana_conf_file }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0644
  become: yes
  notify: restart grafana
  tags: configuration

- name: Ensure integrity of grafana configuration.
  template:
    src: 'grafana-server.j2'
    dest: '/etc/default/grafana-server'
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0644
  become: yes
  notify: restart grafana
  tags: configuration

- name: ensure grafana pid directory is present
  file:
    path="{{ grafana_pid_file_dir }}"
    owner="{{ grafana_user }}"
    group="{{ grafana_group }}"
    mode=0755
    state=directory
  become: yes
    
- name: ensure grafana directories ownership and permissions
  file:
    path="{{ item }}"
    owner="{{ grafana_user }}"
    group="{{ grafana_group }}"
    mode=0755
    state=directory
  become: yes
  with_items:
    - "{{ grafana_dir_conf }}"
    - "{{ grafana_dir_data }}"
    - "{{ grafana_dir_home }}"
    - "{{ grafana_dir_log }}"
    - "{{ grafana_dir_plugins }}"
    - "{{ grafana_pid_file_dir }}"

- name: ensure grafana is running and enabled to start on boot
  service:
    name=grafana-server
    state=started
    enabled=yes
  become: yes
  tags: service
