---
- name: Install wget package
  yum: pkg=wget state=present

- name: Checking /opt directory exists
  become: yes
  file:
    path: /opt
    state: directory

- name: Downloading Grafana rpm file
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-6.5.0-1.x86_64.rpm
    dest: /opt

- name: Installing grafana...
  yum:
    name: /opt/grafana-6.5.0-1.x86_64.rpm
    state: present

- name: Removing RPM file...
  file:
    state: absent
    path: /opt/grafana-6.5.0-1.x86_64.rpm
